import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { CreateDocDto } from './dto/create-doc.dto';
import { UpdateDocDto } from './dto/update-doc.dto';
import { Doc } from './entities/doc.entity';
import { Repository } from 'typeorm';
import { extname } from 'path';
import { Storage } from '@google-cloud/storage';
import { storageConfig } from 'src/config/storage.config';

@Injectable()
export class DocsService {
  constructor(
    @InjectRepository(Doc)
    private readonly docsRepository: Repository<Doc>
  ) { }

  private bucketName = `${process.env.BUCKET_NAME}`;

  async create(createDocDto: CreateDocDto) {
    try {
      const doc = await this.docsRepository.create(createDocDto);

      await this.docsRepository.save(doc);

      const response = {
        message: process.env.SUCCESS_MESSAGE,
      }

      return response;
    } catch (error) {
      throw new Error(error);
    }
  }

  async findAll() {
    try {
      return await this.docsRepository.find();
    } catch (error) {
      throw new Error(error);
    }
  }

  async findOne(referenceCode: number) {
    try {
      const doc = await this.docsRepository.findOneBy({
        uid: referenceCode.toString()
      });

      const response = {
        message: process.env.SUCCESS_MESSAGE,
        data: doc
      }

      return response;
    } catch (error) {
      throw new Error(error);
    }
  }

  async update(referenceCode: number, updateDocDto: UpdateDocDto) {
    try {
      await this.docsRepository.update(referenceCode, updateDocDto);

      const response = {
        message: process.env.SUCCESS_MESSAGE,
      }

      return response;
    } catch (error) {
      throw new Error(error);
    }
  }

  async remove(referenceCode: number) {
    try {
      await this.docsRepository.delete(referenceCode);

      const response = {
        message: process.env.SUCCESS_MESSAGE,
      }

      return response;
    } catch (error) {
      throw new Error(error);
    }
  }

  async uploadToBucket(fileData: Express.Multer.File, fileName?: string) {
    try {
      const autoGeneratedFileName = fileName
        ? fileName
        : `${Math.random().toString(36).substring(2, 10)}${Math.round(Math.random() * 1e9)}${extname(fileData?.originalname)?.replace(' ', '')}`;

      const payLoadWithFileName = {
        ...fileData,
        filename: autoGeneratedFileName,
      };

      const storage = new Storage({
        projectId: `${process.env.PROJECT_ID}`,
        credentials: storageConfig,
      });

      const bucket = storage.bucket(this.bucketName);
      const file = bucket.file(payLoadWithFileName?.filename);

      const transportOptions = {
        resumable: false,
        metadata: {
          contentType: fileData.mimetype,
        },
      };

      const stream = file.createWriteStream(transportOptions);

      await new Promise<void>((resolve, reject) => {
        stream.on('error', (error) => {
          reject(error);
        });

        stream.on('finish', () => {
          resolve();
        });

        stream.end(payLoadWithFileName?.buffer);
      });

      const response = {
        newFileName: {
          name: payLoadWithFileName?.filename,
        },
        status: process.env.SUCCESS_MESSAGE,
        message: 'Media uploaded',
      };

      return response;
    } catch (error: any) {
      const response = {
        newFileName: null,
        message: error.message,
        status: error.status || 'error',
      };

      return response;
    }
  }

  async deleteFromBucket(fileName: string) {
    try {

      const storage = new Storage({
        projectId: `${process.env.PROJECT_ID}`,
        credentials: storageConfig,
      });

      const bucket = storage.bucket(this.bucketName);
      const file = bucket.file(fileName);

      const exists = await file.exists();

      if (exists?.[0]) {
        await file.delete();

        const response = {
          success: true,
          message: `File deleted`,
        };

        return response;
      } else {
        const response = {
          success: true,
          message: `File does not exist`,
        };

        return response;
      }
    } catch (error: any) {
      const response = {
        message: error.message,
        status: error.status || 'error',
        data: null,
      };

      return response;
    }
  }
}
