import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { CreateDocDto } from './dto/create-doc.dto';
import { UpdateDocDto } from './dto/update-doc.dto';
import { Doc } from './entities/doc.entity';
import { DeepPartial, Repository } from 'typeorm';
import { extname } from 'path';
import { Storage } from '@google-cloud/storage';
import { storageConfig } from 'src/config/storage.config';

@Injectable()
export class DocsService {
  constructor(
    @InjectRepository(Doc)
    private readonly docsRepository: Repository<Doc>
  ) { }

  private bucketName = `${process.env.BUCKET_NAME}`;

  async create(createDocDto: CreateDocDto) {
    try {
      const doc = this.docsRepository.create(createDocDto as unknown as DeepPartial<Doc>);
      await this.docsRepository.save(doc);

      const response = {
        message: process.env.SUCCESS_MESSAGE,
      }

      return response;
    } catch (error) {
      const response = {
        message: error.message,
      }

      return response;
    }
  }

  async findAll(): Promise<{ docs: Doc[] | null, message: string }> {
    try {
      const docs = await this.docsRepository.find();

      const response = {
        message: 'docs found',
        docs: docs
      }

      return response;
    } catch (error) {
      const response = {
        message: 'docs not found',
        docs: null
      }

      return response;
    }
  }

  async findOne(referenceCode: number): Promise<{ doc: Doc | null, message: string }> {
    try {
      const doc = await this.docsRepository.findOneBy({
        uid: referenceCode
      });

      const response = {
        message: 'doc found',
        doc: doc
      }

      return response;
    } catch (error) {
      const response = {
        message: 'doc not found',
        doc: null
      }

      return response;
    }
  }

  async update(referenceCode: number, updateDocDto: UpdateDocDto): Promise<{ message: string }> {
    try {
      await this.docsRepository.update(referenceCode, updateDocDto as unknown as DeepPartial<Doc>);

      const response = {
        message: 'doc updated',
      }

      return response;
    } catch (error) {
      const response = {
        message: 'doc not updated',
      }

      return response;
    }
  }

  async remove(referenceCode: number): Promise<{ message: string }> {
    try {
      await this.docsRepository.delete(referenceCode);

      const response = {
        message: 'doc deleted',
      }

      return response;
    } catch (error) {
      const response = {
        message: 'doc not deleted',
      }

      return response;
    }
  }

  async uploadToBucket(fileData: Express.Multer.File, fileName?: string): Promise<{ newFileName: string, message: string }> {
    try {
      const autoGeneratedFileName = fileName
        ? fileName
        : `${Math.random().toString(36).substring(2, 10)}${Math.round(Math.random() * 1e9)}${extname(fileData?.originalname)?.replace(' ', '')}`;

      const payLoadWithFileName = {
        ...fileData,
        filename: autoGeneratedFileName,
      };

      const storage = new Storage({
        projectId: `${process.env.PROJECT_ID}`,
        credentials: storageConfig,
      });

      const bucket = storage.bucket(this.bucketName);
      const file = bucket.file(payLoadWithFileName?.filename);

      const transportOptions = {
        resumable: false,
        metadata: {
          contentType: fileData.mimetype,
        },
      };

      const stream = file.createWriteStream(transportOptions);

      await new Promise<void>((resolve, reject) => {
        stream.on('error', (error) => {
          reject(error);
        });

        stream.on('finish', () => {
          resolve();
        });

        stream.end(payLoadWithFileName?.buffer);
      });

      const response = {
        newFileName: payLoadWithFileName?.filename,
        message: 'media uploaded',
      };

      return response;
    } catch (error: any) {
      const response = {
        newFileName: null,
        message: error.message,
      };

      return response;
    }
  }

  async deleteFromBucket(fileName: string): Promise<{ message: string }> {
    try {

      const storage = new Storage({
        projectId: `${process.env.PROJECT_ID}`,
        credentials: storageConfig,
      });

      const bucket = storage.bucket(this.bucketName);
      const file = bucket.file(fileName);

      const exists = await file.exists();

      if (exists?.[0]) {
        await file.delete();

        const response = {
          message: `File deleted`,
        };

        return response;
      } else {
        const response = {
          message: `File does not exist`,
        };

        return response;
      }
    } catch (error: any) {
      const response = {
        message: error.message,
      };

      return response;
    }
  }
}
