export enum ClientCategory {
    HARDWARE = 'HARDWARE',
    HEALTHCARE = 'HEALTHCARE',
    FINANCE = 'FINANCE',
    RETAIL = 'RETAIL',
    EDUCATION = 'EDUCATION',
    TECHNOLOGY = 'TECHNOLOGY',
    MANUFACTURING = 'MANUFACTURING',
    SERVICES = 'SERVICES',
    OTHER = 'OTHER'
} 