export enum EmailType {
    SIGNUP = 'signup',
    VERIFICATION = 'verification',
    PASSWORD_RESET = 'password_reset',
    PASSWORD_CHANGED = 'password_changed',
    INVOICE = 'invoice',
    DAILY_REPORT = 'daily_report',
    USER_DAILY_REPORT = 'user_daily_report',
    // Quotation related emails
    ORDER_RECEIVED_CLIENT = 'order_received_client',
    NEW_QUOTATION_CLIENT = 'new_quotation_client',
    NEW_QUOTATION_INTERNAL = 'new_quotation_internal',
    NEW_QUOTATION_RESELLER = 'new_quotation_reseller',
    NEW_QUOTATION_WAREHOUSE_FULFILLMENT = 'new_quotation_warehouse_fulfillment',
    QUOTATION_APPROVED = 'quotation_approved',
    QUOTATION_REJECTED = 'quotation_rejected',
    QUOTATION_STATUS_UPDATE = 'quotation_status_update',
    QUOTATION_READY_FOR_REVIEW = 'quotation_ready_for_review',
    QUOTATION_UPDATED = 'quotation_updated',
    QUOTATION_SOURCING = 'quotation_sourcing',
    QUOTATION_PACKING = 'quotation_packing',
    QUOTATION_IN_FULFILLMENT = 'quotation_in_fulfillment',
    QUOTATION_PAID = 'quotation_paid',
    QUOTATION_SHIPPED = 'quotation_shipped',
    QUOTATION_DELIVERED = 'quotation_delivered',
    QUOTATION_RETURNED = 'quotation_returned',
    QUOTATION_COMPLETED = 'quotation_completed',
    // License related emails
    LICENSE_CREATED = 'license_created',
    LICENSE_UPDATED = 'license_updated',
    LICENSE_LIMIT_REACHED = 'license_limit_reached',
    LICENSE_RENEWED = 'license_renewed',
    LICENSE_SUSPENDED = 'license_suspended',
    LICENSE_ACTIVATED = 'license_activated',
    LICENSE_TRANSFERRED_FROM = 'license.transferred.from',
    LICENSE_TRANSFERRED_TO = 'license.transferred.to',
    // Task related emails
    NEW_TASK = 'new_task',
    TASK_UPDATED = 'task_updated',
    TASK_COMPLETED = 'task_completed',
    TASK_REMINDER_ASSIGNEE = 'TASK_REMINDER_ASSIGNEE',
    TASK_REMINDER_CREATOR = 'TASK_REMINDER_CREATOR',
    TASK_OVERDUE_MISSED = 'task_overdue_missed',
    // User related emails
    NEW_USER_ADMIN_NOTIFICATION = 'new_user_admin_notification',
    // Lead related emails
    LEAD_CONVERTED_CLIENT = 'lead_converted_client',
    LEAD_CONVERTED_CREATOR = 'lead_converted_creator',
    LEAD_REMINDER = 'lead_reminder',
    LEAD_ASSIGNED_TO_USER = 'lead_assigned_to_user',
    // Task Flag related emails
    TASK_FLAG_CREATED = 'task_flag_created',
    TASK_FLAG_UPDATED = 'task_flag_updated',
    TASK_FLAG_RESOLVED = 'task_flag_resolved',
    // Task Feedback related emails
    TASK_FEEDBACK_ADDED = 'task_feedback_added',
    // Client authentication related emails
    CLIENT_PASSWORD_RESET = 'client_password_reset',
    CLIENT_PASSWORD_CHANGED = 'client_password_changed',
} 
