export enum LeadStatus {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    REVIEW = "REVIEW",
    DECLINED = "DECLINED",
    CONVERTED = "CONVERTED",
    CANCELLED = "CANCELLED",
} 

export enum LeadCategory {
    BUSINESS = "BUSINESS",
    PERSONAL = "PERSONAL",
    WALK_IN = "WALK_IN",
    REFERRAL = "REFERRAL",
    PHONE = "PHONE",
    EMAIL = "EMAIL",
    SOCIAL_MEDIA = "SOCIAL_MEDIA",
    WEBSITE = "WEBSITE",
    OTHER = "OTHER",
}