export enum ReportType {
    DAILY_USER = 'DAILY_USER',
    MONTHLY_DASHBOARD = 'MONTHLY_DASHBOARD',
    CUSTOM_DASHBOARD = 'CUSTOM_DASHBOARD'
}

export enum ReportFormat {
    PDF = 'PDF',
    CSV = 'CSV',
    JSON = 'JSON'
}

export enum ReportStatus {
    PENDING = 'PENDING',
    GENERATING = 'GENERATING',
    COMPLETED = 'COMPLETED',
    FAILED = 'FAILED'
}

export enum ReportMetricType {
    PRODUCTIVITY = 'PRODUCTIVITY',
    EFFICIENCY = 'EFFICIENCY',
    CUSTOMER_SATISFACTION = 'CUSTOMER_SATISFACTION',
    RESPONSE_TIME = 'RESPONSE_TIME',
    TASK_COMPLETION = 'TASK_COMPLETION',
    QUOTATION_CONVERSION = 'QUOTATION_CONVERSION',
    CLAIM_PROCESSING = 'CLAIM_PROCESSING',
    ATTENDANCE = 'ATTENDANCE'
}

export enum ReportTimeframe {
    DAILY = 'DAILY',
    WEEKLY = 'WEEKLY',
    MONTHLY = 'MONTHLY',
    QUARTERLY = 'QUARTERLY',
    YEARLY = 'YEARLY',
    CUSTOM = 'CUSTOM'
} 