export enum ReportType {
    OVERVIEW = 'overview',
    USER_SPECIFIC = 'userSpecific',
    BRANCH_SPECIFIC = 'branchSpecific',
    COMPANY_SPECIFIC = 'companySpecific',
    DAILY = 'daily',
    WEEKLY = 'weekly',
    MONTHLY = 'monthly',
    YEARLY = 'yearly',
    GENERAL = 'general',
    ORDER = 'order',
    ATTENDANCE = 'attendance',
    ASSET = 'asset',
    CLIENT = 'client',
    CHECK_IN = 'checkIn',
    DOC = 'doc',
    JOURNAL = 'journal',
    LEAD = 'lead',
    NEWS = 'news',
    TASK = 'task',
    CLAIM = 'claim',
    QUOTATION = 'quotation',
}
