export enum TaskStatus {
	PENDING = 'PENDING',
	IN_PROGRESS = 'IN_PROGRESS',
	COMPLETED = 'COMPLETED',
	CANCELLED = 'CANCELLED',
	OVERDUE = 'OVERDUE',
	POSTPONED = 'POSTPONED',
	MISSED = 'MISSED',
}

export enum TaskPriority {
	LOW = 'LOW',
	MEDIUM = 'MEDIUM',
	HIGH = 'HIGH',
	URGENT = 'URGENT',
}

export enum RepetitionType {
	NONE = 'NONE',
	DAILY = 'DAILY',
	WEEKLY = 'WEEKLY',
	MONTHLY = 'MONTHLY',
	YEARLY = 'YEARLY',
}

export enum TaskType {
	IN_PERSON_MEETING = 'IN_PERSON_MEETING',
	VIRTUAL_MEETING = 'VIRTUAL_MEETING',
	CALL = 'CALL',
	EMAIL = 'EMAIL',
	WHATSAPP = 'WHATSAPP',
	SMS = 'SMS',
	FOLLOW_UP = 'FOLLOW_UP',
	PROPOSAL = 'PROPOSAL',
	REPORT = 'REPORT',
	QUOTATION = 'QUOTATION',
	VISIT = 'VISIT',
	OTHER = 'OTHER',
}

export enum JobStatus {
	QUEUED = 'QUEUED',
	RUNNING = 'RUNNING',
	COMPLETED = 'COMPLETED',
}
